{{- if .Values.cronCm -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: photoprism-script
  labels:
    {{- include "photoprism.labels" . | nindent 4 }}
{{- with .Values.cronCm }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}