{{- range $jobname, $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "photoprism.fullname" $ }}-{{ $jobname }}
  labels:
    {{- include "photoprism.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "photoprism.fullname" $ }}
            cron: {{ $jobname }}
        spec:
          serviceAccountName: {{ include "photoprism.serviceAccountName" $ }}
          containers:
          - image: {{ $job.image.repository }}:{{ $job.image.tag }}
            imagePullPolicy: {{ $job.image.imagePullPolicy }}
            {{- with $.Values.securityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            name: {{ $jobname }}
            {{- with $.Values.env }}
            env:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with $job.command }}
            command:
              {{ toYaml . | nindent 14 }}
            {{- end }}
            {{- with $job.args }}
            args:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with $job.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with $.Values.volumeMounts }}
            volumeMounts:
              {{ toYaml . | nindent 14 }}
            {{- end }}
            {{- with $job.volumeMounts }}
              {{ toYaml . | nindent 14 }}
            {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          {{- with $.Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
{{- end }}