{{- if .Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "photoprism.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secrets.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}