apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: default
  name: supabase
spec:
  targetNamespace: supabase
  createNamespace: true
  version: 0.1.3
  chart: supabase
  repo: https://charts.qunito.com
  valuesContent: |-
    secret:
      jwt:
        anonKey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjY2OTYyNjMsImV4cCI6MzYwMDAwMTcyNjY5NjI2MywiaXNzIjoiYW5vbi5zdXBhYmFzZSJ9.7KyeiUiwgK4b_qwcQ4YFFpktIx9i2p6ZcAR4QiwKIXs
        serviceKey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjY2OTYzMTksImV4cCI6MzYwMDAwMTcyNjY5NjMxOSwiaXNzIjoic2VydmljZS5zdXBhYmFzZSJ9.RFJiEu0O2FoY7YVihZDEYp4VR7AchSv--0YhPCOmotQ
        secret: 7ADvpl5ZQhfIrpRBMelzIaUafkGVfUjSVLPC9NcOKZ1Ex5uN
      smtp:
        username: supabase@qunito.com
        password: Supabase@2610
      dashboard:
        username: supabase
        password: Supabase@2610
      db:
        username: postgres
        password: Supabase@2610
        database: postgres
      analytics:
        apiKey: ySbDd6H3WP2tGxXJhlLxb1K2F35DZov1ITiUrPfyVLc83aaz

    db:
      enabled: true
      image:
        tag: 15.1.0.147
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 3
      persistence:
        enabled: false

    studio:
      image:
        tag: 20240326-5e5586d
      environment:
        STUDIO_DEFAULT_ORGANIZATION: "Byteken"
        STUDIO_DEFAULT_PROJECT: "default"
        SUPABASE_PUBLIC_URL: https://supabase.qunito.com/
        NEXT_PUBLIC_ENABLE_LOGS: "true"
      livenessProbe:
        httpGet:
          path: /api/profile
          port: 3000
        initialDelaySeconds: 3

    auth:
      image:
        tag: v2.143.0
      environment:
        API_EXTERNAL_URL: https://supabase.qunito.com
        GOTRUE_SITE_URL: https://supabase.qunito.com
        GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
        GOTRUE_MAILER_AUTOCONFIRM: "true"
        GOTRUE_SMTP_ADMIN_EMAIL: "supabase@qunito.com"
        GOTRUE_SMTP_HOST: "smtp.hostinger.com"
        GOTRUE_SMTP_PORT: "465"
        GOTRUE_SMTP_SENDER_NAME: "noreply@qunito.com"

    rest:
      image:
        tag: v12.0.1

    realtime:
      image:
        tag: v2.27.5
      livenessProbe:
        httpGet:
          path: /
          port: 4000
        initialDelaySeconds: 3

    meta:
      image:
        tag: v0.80.0

    storage:
      image:
        tag: v0.46.4
      livenessProbe:
        httpGet:
          path: /status
          port: 5000
        initialDelaySeconds: 3
      persistence:
        enabled: false

    imgproxy:
      image:
        tag: v3.8.0
      environment:
        IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      livenessProbe:
        exec:
          command:
            - imgproxy
            - health
        initialDelaySeconds: 3
      persistence:
        enabled: false

    kong:
      image:
        repository: kong
        tag: 2.8.1
      environment:
        KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
        KONG_LOG_LEVEL: info
      ingress:
        enabled: true
        className: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.middlewares: default-traefik-inflight@kubernetescrd,default-traefik-secure@kubernetescrd,default-traefik-ratelimit@kubernetescrd
        tls:
          - secretName: kong-ingress-tls
            hosts:
              - supabase.qunito.com
        hosts:
          - host: supabase.qunito.com
            paths:
              - path: /
                pathType: Prefix

    analytics:
      image:
        tag: 1.4.0
      livenessProbe:
        httpGet:
          path: /health
          port: 4000
        initialDelaySeconds: 3

    vector:
      image:
        tag: 0.34.0-alpine
      livenessProbe:
        httpGet:
          path: /health
          port: 9001
        initialDelaySeconds: 3
      ## Vector requires logs from the control plane to function.
      ## This is normally stored in /var/log/pods
      ## Modify these values according to your environment.
      volumeMounts:
        - name: pod-logs
          mountPath: /var/log/pods
      volumes:
        - name: pod-logs
          hostPath:
            path: /var/log/pods

    functions:
      image:
        tag: v1.41.2
