annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - kind: changed
      description: Bumped pgvecto-rs to pg14-v0.2.0
      links:
        - name: Release Notes Breaking Changes
          url: https://github.com/immich-app/immich/releases/tag/v1.95.1
apiVersion: v2
appVersion: v1.106.1
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.4.0
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.24
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.4.0
description: A chart to power Immich (immich.app) running on kubernetes
home: https://immich.app/
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
maintainers:
  - email: 5434875+PixelJonas@users.noreply.github.com
    name: PixelJonas
  - email: immich@bo0tzz.me
    name: bo0tzz
name: immich
sources:
  - https://github.com/immich-app/immich-charts/tree/main/charts/immich
  - https://github.com/immich-app/immich
version: 0.7.0
