{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pcloud.fullname" . }}
  labels:
    {{- include "pcloud.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secrets }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}