apiVersion: v1
kind: Service
metadata:
  name: {{ include "akaunting.fullname" . }}
  labels:
    {{- include "akaunting.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "akaunting.selectorLabels" . | nindent 4 }}
