{{- if .Values.cronCm -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup.fullname" . }}-script
  labels:
    {{- include "backup.labels" . | nindent 4 }}
{{- with .Values.cronCm }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}